### ISSUE TITLE
How to run initial request immediately, throttle subsequent requests?

### ISSUE THREAD

**Issue by josephxanderson** [boraseoksoon/Throttler#1]
This is a really easy to use package. However, it does have one issue which makes apps appear a bit slow. It is using more of a "debounce" than a "throttle". How can we run the initial request immediately, and only throttle the subsequent requests?

**Comment by boraseoksoon** [comment]
hey! @josephxanderson  sorry to respond late, and 
thanks for your suggestion, that's really cool idea. 

I may begin writing that feature soon when I have a time!

**Comment by boraseoksoon** [comment]
Implemented
